### ISSUE TITLE
Any way to pop local/global mark easily?

### ISSUE THREAD

**Issue by DamienCassou** [karthink/repeat-help#3]
I often go back to previous location with <kbd>C-u C-SPC</kbd> (`set-mark-command`). I often have to repeat this whole key sequence several times to reach an old location. There is the option `set-mark-command-repeat-pop` to only have to repeat the <kbd>C-SPC</kbd> part.

What do you use to pop many marks?

**Comment by karthink** [comment]
I guess you could use repeat-mode to set SPC to pop the mark repeatedly after the first C-u C-SPC:

``` emacs-lisp
(defvar mark-repeat-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "SPC") #'pop-to-mark-command)
    map))

(put 'pop-to-mark-command 'repeat-map 'mark-repeat-map)
```

But I haven't bothered with this. Like you, I use `set-mark-command-repeat-pop` and `C-SPC` to pop the mark repeatedly.

Until recently I was using this with a digit argument (like `C-4 C-SPC`) to pop many marks.

But recently I've taken to using `consult-mark`, which does't pop the mark but does let you jump to a specific one from a menu. (I've bound this to `C-x '`, replacing an abbrev command that I rarely use, and is also available on `C-x a e` anyway.)

**Comment by DamienCassou** [comment]
Thank you very much!

You may close the issue.

**Comment by karthink** [comment]
Cheers @DamienCassou.
